# Generated by Django 5.1.2 on 2024-12-23 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('co2data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CO2Data',
        ),
    ]
