FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    sudo \
    vim \
    nano \
    wget \
    git \
    g++ \
    make \
    autoconf \
    automake \
    libtool \
    zlib1g-dev \
    libbz2-dev

USER ubuntu
